apiVersion: watcher.openstack.org/v1beta1
kind: Watcher
metadata:
  labels:
    app.kubernetes.io/name: watcher
    app.kubernetes.io/instance: watcher
    app.kubernetes.io/part-of: watcher-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: watcher-operator
  name: watcher
spec:
  databaseInstance: "openstack"
  apiServiceTemplate:
    tls:
      caBundleSecretName: "combined-ca-bundle"
