[DEFAULT]
state_path = /opt/stack/data/watcher
control_exchange = watcher
debug = True

[database]
connection = {{ .DatabaseConnection }}

[oslo_policy]
policy_file = /etc/watcher/policy.yaml

[oslo_messaging_notifications]
driver = messagingv2
